import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import 'primeicons/primeicons.css'

import { Nav } from './ui/Nav'
import { Footer } from './ui/Footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'HLAE Next Site',
  description: 'Generated by create next app',
  icons: '/logo2009.svg',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
